### PR TITLE
Adapt to Java 17 and 21

### LINKED ISSUE #68: Build with Java 17 fails due to missing Javadoc comments
# Description
Building the project with Java 17 fails due to missing Javadoc comments

## Steps to Reproduce
1. Run `JAVA_HOME=$JAVA17_HOME mvn javadoc:aggregate`

## Expected behavior
* The build runs without error
* The `build-next-java.yml` workflow is activated again

# Environment
- Java Version: 17

### PR DESCRIPTION
**Pull request by kaklakariada**
Fixes #68

### CODE REVIEW

**Review by ckunki — APPROVED** [review]

File: src/main/java/org/itsallcode/io/Capturable.java [hunk 1]
```diff
@@ -1,22 +1,25 @@
...
+/**
+ * Interface for classes that can capture output.
+ */
 public interface Capturable
 {
     /**
      * Activate capturing
      */
-    public void capture();
+    void capture();
```
Comment (redcatbear) [inline src/main/java/org/itsallcode/io/Capturable.java:11]: Why remove this? I always found this notation inconsistent.

File: src/main/java/org/itsallcode/junit/sysextensions/security/ExitTrapException.java [hunk 2]
```diff
@@ -1,17 +1,41 @@
...
     private final int status;
 
+    /**
+     * Constructs a new {@link ExitTrapException} with the given message and
+     * exit.
+     * 
+     * @param message
+     *            the message
+     * @param status
+     *            the exit status code
```
Comment (redcatbear) [inline src/main/java/org/itsallcode/junit/sysextensions/security/ExitTrapException.java]:
```suggestion
     * @param message
     *            exit message
     * @param status
     *            exit status code
```

**Review by redcatbear — APPROVED** [review]

File: src/main/java/org/itsallcode/io/Capturable.java (hunk 1 above)
Comment (kaklakariada) [reply src/main/java/org/itsallcode/io/Capturable.java:11]: Sonar complains about this. Interface methods are public by default.
